PACKAGE_NAME="dp-driver"
PACKAGE_VERSION="1.0"

MAKE[0]="make DP_MODULE_VERSION=1.0 KBUILD_EXTRA_SYMBOLS=/var/lib/dkms/mhi-host/1.0/source/Module.symvers MHI_BUILD_ROOT=/usr/src/mhi-host-1.0"

BUILT_MODULE_NAME[0]=csm_dp
BUILT_MODULE_LOCATION[0]=drivers/char/csm-dp
DEST_MODULE_LOCATION[0]=/extra
STRIP[0]=no

AUTOINSTALL=yes
