#!/bin/sh

if lsmod | grep -q csm_dp; then
    modprobe -r csm_dp || true
fi

rm -rf /var/lib/dkms/dp-driver/
rm -rf /usr/src/dp-driver-1.0
rm -f /usr/include/linux/csm_dp_ioctl.h
rm -f /lib/modules/`uname -r`/updates/dkms/csm_dp.ko.zst
